services:
  dpsrv-scheduler:
    build: .
    container_name: dpsrv-scheduler-${tag:-latest}
    image: dpsrv/scheduler:${tag:-latest}
    env_file:
      - ${DPSRV_HOME}/rc/secrets/scheduler/scheduler.env
      - ${DPSRV_HOME}/rc/secrets/local/${HOSTNAME}/local.env
    volumes:
      - $PWD/../:/root/dpsrv
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DPSRV_HOME}/rc/secrets/scheduler/periodic/1min/:/etc/periodic/1min/:ro
      - ${DPSRV_HOME}/rc/secrets/scheduler/periodic/daily/:/etc/periodic/daily/:ro
      - ${HOME}/.git-credentials:/root/.git-credentials:ro
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}/.config:/root/.config:ro
      - /etc/localtime:/etc/localtime:ro
    command: [ "crond", "-f", "-d", "8" ]
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
