services:
  scheduler:
    image: alpine:3.18
    container_name: scheduler
    env_file: ${DPSRV_HOME}/rc/secrets/scheduler/scheduler.env
    volumes:
      - ${DPSRV_HOME}/rc/secrets/scheduler/periodic/daily/:/etc/periodic/daily/:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/localtime:/etc/localtime:ro
    command: [ "crond", "-f", "-d", "8" ]
    restart: unless-stopped
