services:
  dpsrv-scheduler:
    container_name: dpsrv-scheduler-${tag:-latest}
    image: dpsrv/scheduler:${tag:-latest}
    build:
      context: .
      args:
        DPSRV_UID: ${DPSRV_UID}
    hostname: $HOSTNAME.dpsrv.me
    env_file:
      - ${DPSRV_HOME}/rc/secrets/scheduler/scheduler.env
      - ${DPSRV_HOME}/local.env
    volumes:
      - /mnt/data/dpsrv/:/mnt/data/dpsrv/
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.git-credentials:/root/.git-credentials:ro
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}/.config:/root/.config:ro
      - ${HOME}/.gnupg:/root/.gnupg
      - /etc/localtime:/etc/localtime:ro
    command: [ "crond", "-f", "-d", "8" ]
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
